#!/bin/bash

nbDossier=3
nbDossierLocal=3
nbDossierDistant=3

echo -e "\033[5m###################################"
echo -e "\033[5m#                                 #"
echo -e "\033[5m#    BIENVENUE SUR NOTRE SCRIPT   #"
echo -e "\033[5m#                                 #"
echo -e "\033[5m###################################"
tput sgr0
echo ""
read -p "Press Enter to continue"

#Demande a l'utilisateur comment appeler le dossier
echo -e "\033[94mComment voulez-vous appeler votre dossier ?"
tput sgr0
read nomDuDossier

#Gestion de l'erreur dans le cas ou le nom du dossier a un ou des espaces
    while [[ "$nomDuDossier" != "${nomDuDossier/ /}" ]]
    do
        if [ $nbDossier -gt 1 ]; then 
          let "nbDossier--"
          echo -e "\033[91mVotre nom de dossier ne doit pas contenir d'espaces. Il vous reste {$nbDossier} chance."
          tput sgr0
          read nomDuDossier
        fi
        
        if [ $nbDossier -le 1 ]; then
          echo "vous avez quitté le script"
          exit 1
        fi
    done

#Demande quels boxe utiliser
echo -e "\033[94mEntrez le nom de la box vagrant que vous souhaitez utiliser, laissez vide si vous voulez la base."
tput sgr0
read nomServeur

#Demande le nom du dossier synchro de la machine local
echo -e "\033[94mEntrez le nom de votre fichier synchronisé en local."
tput sgr0
read fichierLocal

#Gestion de l'erreur dans le cas ou le nom du dossier a un ou des espaces
    while [[ "$fichierLocal" != "${fichierLocal/ /}" ]]
    do
        if [ $nbDossierLocal -gt 1 ]; then
          let "nbDossierLocal--"
          echo -e "\033[91mVotre nom de dossier ne doit pas contenir d'espaces. Il vous reste {$nbDossierLocal} chance."
          tput sgr0
          read nomDuDossier
        fi
        
        if [ $nbDossierLocal -le 1 ]; then
          echo "vous avez quitté le script"
          exit 1
        fi
    done

#Demande le nom du dossier synchro de la machine virtuelle
echo -e "\033[94mEntrez le nom de votre fichier synchronisé distant. Laissez vide si vous souhaitez, par défaut dans /var/www/html"
tput sgr0
read fichierDistant

#Gestion de l'erreur dans le cas ou le nom du dossier a un ou des espaces
    while [[ "$fichierDistant" != "${fichierDistant/ /}" ]]
    do
        if [ $nbDossierDistant -gt 1 ]; then
          let "nbDossierDistant--"
          echo -e "\033[91mVotre nom de dossier ne doit pas contenir d'espaces. Il vous reste {$nbDossierDistant} chance."
          tput sgr0
          read nomDuDossier
        fi
        
        if [ $nbDossierDistant -le 1 ]; then
          echo "vous avez quitté le script"
          exit 1
        fi
    done

echo "Patientez."
mkdir $nomDuDossier
cd $nomDuDossier
vagrant init
  if [ -z "$nomServeur" ]; then
    nomServeur="base"
  fi


sed -i -e "s/config.vm.box = \"base\"/config.vm.box = \"$nomServeur\"/g" Vagrantfile
sed -i -e "s/# config.vm.network \"private_network\", ip: \"192.168.33.10\"/config.vm.network \"private_network\", ip: \"192.168.33.10\"/g" Vagrantfile

  if [ -z "$fichierDistant" ]; then
    sed -i -e "s/# config.vm.synced_folder \"..\/data\", \"\/vagrant_data\"/config.vm.synced_folder \"$fichierLocal\", \"\/var\/www\/html\"/g" Vagrantfile
  fi

  if [ -n "$fichierDistant" ]; then
    sed -i -e "s/# config.vm.synced_folder \"..\/data\", \"\/vagrant_data\"/config.vm.synced_folder \"$fichierLocal\", \"\/var\/www\/html\/$fichierDistant\"/g" Vagrantfile
  fi
  
mkdir $fichierLocal
rm Vagrantfile-e
vagrant up
